# Generated by Django 5.2.1 on 2025-06-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plaid_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
